version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: Counsel-GPT-app
    restart: unless-stopped
    volumes:
      - ${PWD}/package/:/Counsel-GPT/package/
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; response = requests.get('http://127.0.0.1:8080'); response.status_code == 200"]
      interval: 15s
      retries: 5
      timeout: 60s
  nginx:
    image: nginx:stable
    container_name: Counsel-GPT-Nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      # app:
      #   condition: service_healthy